export const myDatas = [
  {
    id: 0,
    type: "snack",
    name: "humberger",
    source: "/src/items/1.jpg",
    value: 2500,
  },
  {
    id: 2,
    type: "beverage",
    name: "beer",
    source: "/src/items/2.jpg",
    value: 2600,
  },
  {
    id: 3,
    type: "fruit",
    name: "red apple",
    source: "/src/items/3.jpg",
    value: 300,
  },
  {
    id: 4,
    type: "cake",
    name: "chocolate cake",
    source: "/src/items/4.jpg",
    value: 5000,
  },
  {
    id: 5,
    type: "fruit",
    name: "green apple",
    source: "/src/items/5.jpg",
    value: 400,
  },
  {
    id: 6,
    type: "pizza",
    name: "flavoured pizza",
    source: "/src/items/6.jpg",
    value: 9000,
  },
  {
    id: 7,
    type: "fruit",
    name: "banana",
    source: "/src/items/banana.jpg",
    value: 500,
  },
  {
    id: 8,
    type: "snack",
    name: "bread",
    source: "/src/items/bread.jpg",
    value: 1000,
  },
  {
    id: 9,
    type: "snack",
    name: "bread baked",
    source: "/src/items/bread1.jpg",
    value: 1400,
  },
  {
    id: 10,
    type: "snack",
    name: "donut",
    source: "/src/items/donut.jpg",
    value: 1500,
  },
  {
    id: 11,
    type: "snack",
    name: "donut",
    source: "/src/items/donutTriple.jpg",
    value: 1500,
  },
  {
    id: 12,
    type: "hat",
    name: "style hat",
    source: "/src/items/hat1.jpg",
    value: 1500,
  },
  {
    id: 13,
    type: "hat",
    name: "black hat",
    source: "/src/items/hatb.jpg",
    value: 1500,
  },
  {
    id: 14,
    type: "hat",
    name: "hat",
    source: "/src/items/hatw.jpg",
    value: 1500,
  },
  {
    id: 15,
    type: "hat",
    name: "Los hat",
    source: "/src/items/headLa.jpg",
    value: 1500,
  },
  {
    id: 16,
    type: "hat",
    name: "Nike hat",
    source: "/src/items/headNike.jpg",
    value: 1500,
  },
  {
    id: 17,
    type: "fruit",
    name: "lemon",
    source: "/src/items/lemon.jpg",
    value: 1500,
  },
  {
    id: 18,
    type: "beverage",
    name: "pepsi",
    source: "/src/items/pepsi.jpg",
    value: 1500,
  },
  {
    id: 19,
    type: "beverage",
    name: "caned pepsi",
    source: "/src/items/pepsi1.jpg",
    value: 3000,
  },
  {
    id: 20,
    type: "pizza",
    name: "omalet pizza",
    source: "/src/items/pizz.jpg",
    value: 2400,
  },
  {
    id: 20,
    type: "cake",
    name: "pile cake",
    source: "/src/items/snackS.jpg",
    value: 4000,
  },
];

export const cartData = [];
